kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: prod-app
  namespace: prod
spec:
  repo: https://github.com/hwchiu/fleet_demo.git
  branch: master
  paths:
    - app/basic
    - app/basic_overlay
    - app/kustomize
    - app/helm
    - app/helm_external
    - app/helm_kustomize
  targets:
    - clusterSelector: {}
