kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: testing-app
  namespace: testing
spec:
  repo: https://github.com/hwchiu/fleet_demo.git
  branch: master
  paths:
    - app/basic
    - app/basic_overlay
    - app/kustomize
    - app/helm
  targets:
    - clusterSelector: {}
